function [p0_rec_dmas_cf, p0_rec_dmas, cf, p0_rec_das] = reconstruct_dmas_cf(model, sinogram)
% Perform DMAS_CF reconstruction with the parameters that are specified in the provided model.

[p0_rec_dmas_cf, p0_rec_dmas, cf, p0_rec_das] = dmas_cf(...
    sinogram,...
    model.Discretization.region.xPositionsFov, ...
    model.Discretization.region.zPositionsFov,...
    model.Medium.speedOfSound, ...
    model.Probe.DAC.frequency,...
    model.DataPreprocessing.numCroppedSamplesAtSinogramStart + model.Probe.DAC.delayBeforeRecording,...
    model.Probe.detector.angularCoverage,...
    model.Probe.detector.radius);

end
